### ISSUE TITLE
arm64 image desired

### ISSUE THREAD

**Issue by kenrachynski** [jenkins-infra/docker-builder#38]
Hi, I am trying to set up a kubernetes cluster on arm64 hardware with Jenkins configured to build container images to use on this cluster. This particular image looks like it will meet my needs, but it's only available on Docker Hub as an amd64 image.

Could you add arm64 as an output to this project please?

**Comment by dduportal** [comment]
As per https://github.com/jenkins-infra/helpdesk/issues/2740 (duplicating this issue):

> I am trying to set up a Kubernetes cluster to build software for my cluster. This cluster happens to be running on arm64 hardware. I went to add a container template in my Kubernetes Cloud configuration against jenkinsciinfra/builder which looks like it includes its own docker in the container and is built on top of jenkinsci/inbound-agent. The only problem I see is that the only image architecture available on this image is amd64.

**Comment by dduportal** [comment]
Hi @kenrachynski , as per https://github.com/jenkins-infra/helpdesk/issues/2963 we dropped the use of `img` and are using a fully fledge Docker Engine running in virtual machines (ephemeral agents or SSH agents).

The rationale is related to `img` not being maintained compared to Docker + BuildX all together, associated to the risks of running such workload in Kubernetes for us: our goal is to build and provide a set of Docker images, Docker is a strict requirement.

It means that we have dropped the support for `img`: not sure that an amd64 of this image would help you.

You might be interested by looking into one of the following solutions instead:

- Using a `docker buildx` non-privileged pod that would leverage the "kubernetes" driver of [buildx](https://github.com/docker/buildx) as described in https://medium.com/nttlabs/buildx-kubernetes-ad0fe59b0c64 or more recently on https://techblog.greeneye.ag/blog/kubernetes-continuous-integration-using-buildkit-buildx-and-docker-regisrty
  - There are official images for `docker` (with client only, or both, and buildx) in arm64
  - You are using Kubernetes to build images and want a non privileged solutions

- Switching to VMs like we do (with the amount of changes and maintenance that it requires of course)

- You can also try Kaniko: it has been added an ARM64 support quite recently (April 2022): https://github.com/GoogleContainerTools/kaniko/issues/530#issuecomment-1113431198
