### ISSUE TITLE
Cleanup cst and hadolint

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/docker-builder#62]
Let's cleanup cst and haodlint on subsequent PRs

And also jx-release-version (no usage outside release and docker pipeline library - [github.com/search?p=2&q=org%3Ajenkins-infra+jx-release-version&type=Code](https://github.com/search?p=2&q=org%3Ajenkins-infra+jx-release-version&type=Code))

_Originally posted by @dduportal in https://github.com/jenkins-infra/docker-builder/pull/59#pullrequestreview-1002683922_

**Comment by dduportal** [comment]
Let's also cleanup the `README`

**Comment by dduportal** [comment]
> > Let's also cleanup the `README`
> 
> What do you want to remove from it?

everything related to building/testing containers.
With the changes we are applying here (removing `img`, `hadolint`, etc.), it changes the role of this image from "used to build containers" to "used to build static websites", so the `README.md` should be updated to map this.
